"""Validated device configuration and lifecycle ownership for ZMeter."""

from .config import ProfileValidationError, load_profile
from .models import (
    ChannelFilters,
    ConnectionFieldSpec,
    DeviceConfig,
    DriverConfigSpec,
    ProfileConfig,
    ProfilePaths,
)
from .manager import (
    DeviceLifecycleError,
    DeviceManager,
    DeviceManagerError,
    DeviceManagerLoadError,
    DeviceManagerThreadError,
    DeviceManagerTerminatedError,
    DeviceRecordView,
    DeviceSnapshot,
    DeviceStartupError,
    DeviceState,
    LifecycleFailure,
    LifecycleReport,
)
from .registry import (
    DisabledDeviceError,
    DriverAdapter,
    DriverConstructionError,
    DriverConfigurationError,
    DriverRegistration,
    DriverRegistry,
    DriverRegistryError,
    DriverTerminatedError,
    DriverUnavailableError,
    DuplicateDriverError,
    LifecycleUnsupportedError,
    UnknownDriverError,
    build_default_registry,
)

__all__ = [
    "ChannelFilters",
    "ConnectionFieldSpec",
    "DeviceConfig",
    "DeviceLifecycleError",
    "DeviceManager",
    "DeviceManagerError",
    "DeviceManagerLoadError",
    "DeviceManagerThreadError",
    "DeviceManagerTerminatedError",
    "DeviceRecordView",
    "DeviceSnapshot",
    "DeviceStartupError",
    "DeviceState",
    "DisabledDeviceError",
    "DriverAdapter",
    "DriverConfigSpec",
    "DriverConstructionError",
    "DriverConfigurationError",
    "DriverRegistration",
    "DriverRegistry",
    "DriverRegistryError",
    "DriverTerminatedError",
    "DriverUnavailableError",
    "DuplicateDriverError",
    "LifecycleUnsupportedError",
    "LifecycleFailure",
    "LifecycleReport",
    "ProfileConfig",
    "ProfilePaths",
    "ProfileValidationError",
    "UnknownDriverError",
    "build_default_registry",
    "load_profile",
]
