import inspect
import json
import os
import re
import sys
import time
from copy import deepcopy
from dataclasses import replace

import numpy as np
from PyQt6 import QtWidgets, uic, QtCore, QtGui

from .device_catalog import (
    DeviceCatalogBusyError,
    DeviceCatalogError,
    DeviceCatalogReferenceError,
    DeviceCatalogRollbackError,
    DeviceCatalogSnapshot,
)
from .device_management import DeviceLifecycleError, DeviceSnapshot

# from sr830.sr830_main import SR830
# from sr860.sr860_main import SR860
# from nidaq.nidaq_main import NIDAQ
# from keithley24xx.keithley24xx_main import Keithley24xx
# from k10cr1.k10cr1_main import K10CR1
# from tlpm.tlpm_main import TLPM

from .scan_info import *
from .scanlist import (
    ScanList,
    ScanListShutdownStopError,
    ScanListShutdownTimeoutError,
)
from .artificial_channel_logic import ArtificialChannelLogic
from .artificial_channel_2d_main import ArtificialChannel2D
from .device_command_router import DeviceCommandRouter
from .scan_range_main import ScanRangeWindow


#Select Virtual Environment under zmeter_venv\.venv\Scripts\python.exe
class MainWindow(QtWidgets.QWidget):
    print("Initiating the Program")
    SCAN_RANGE_CONFIG_FILENAME = "scan_range_limits.json"

    def __init__(
        self,
        info=None,
        save_path=None,
        backup_main_path=None,
        equips=None,
        equips_set_channels=None,
        equips_get_channels=None,
        device_manager=None,
    ):
        super().__init__()
        print("Loading the Main Window")
        uic.loadUi(r"core/ui/mainwindow.ui", self)
        self.info = info
        
        # ------------------------------------------------------------
        # Configuration previously hard-coded here is now supplied via
        # the constructor arguments so that users can customise the
        # application without editing this file.  See `start_zmeter.py`.

        # Paths
        if save_path is None:
            save_path = os.path.join(os.getcwd(), "data")
        self.save_path = save_path

        if backup_main_path is None:
            self.backup_bool = False
        else:
            self.backup_bool = True
            self.backup_main_path = backup_main_path

        # Reflect the paths in the UI elements that were generated by
        # QtDesigner.
        self.ppt_path.setPlainText(os.path.join(self.save_path, "log.pptx"))
        self.save_info_path.setPlainText(self.save_path)

        # Keep a live alias used by Scan._backup_subfolder(), so user edits in
        # the UI are always read at save time.
        self.backup_path = self.backup_Path
        if self.backup_bool:
            default_backup_path = os.path.join(
                self.backup_main_path, os.path.basename(os.getcwd())
            )
            self.backup_Path.setPlainText(default_backup_path)

        # Equipment instances may come from the static DeviceManager snapshot
        # or from the legacy constructor dictionaries used by standalone tests
        # and scripts. Manager ownership is intentionally static in this phase.
        self.device_manager = device_manager
        if device_manager is not None:
            if any(
                value is not None
                for value in (
                    equips,
                    equips_set_channels,
                    equips_get_channels,
                )
            ):
                raise ValueError(
                    "device_manager cannot be combined with legacy equipment arguments"
                )
            initial_device_snapshot = device_manager.snapshot()
        else:
            initial_device_snapshot = DeviceSnapshot(
                profile_name="legacy",
                records=(),
                equipment=equips if equips is not None else {},
                setter_filters=(
                    equips_set_channels if equips_set_channels is not None else {}
                ),
                getter_filters=(
                    equips_get_channels if equips_get_channels is not None else {}
                ),
            )
        self._applied_device_snapshot = initial_device_snapshot
        self.equips = dict(initial_device_snapshot.equipment)
        self.equips_set_channels = dict(initial_device_snapshot.setter_filters)
        self.equips_get_channels = dict(initial_device_snapshot.getter_filters)
        self._session_shutdown_in_progress = False
        self._session_shutdown_complete = False
        self._session_shutdown_report = None
        self._catalog_mutation_in_progress = False
        # ------------------------------------------------------------

        # {equipment name (e.g. lockin_0) : {variable name : set method},....}
        self.setter_equipment_info_for_scanning = {}
        # {equipment name (e.g. lockin_0) : {variable name : get method},....}
        self.getter_equipment_info_for_scanning = {}
        # {equipment(lockin_0) : [list of variable name]}
        self.setter_equipment_info = {}
        # {equipment : [list of variable name]}
        self.getter_equipment_info = {}
        self.device_channel_catalog = {}
        self.scan_range_limits = {}
        self.active_scan_range_limits = {}
        self._skip_next_scan_read_from_global_limit = False
        self._force_stop_requested = False
        self.scan_range_limits_path = self._default_scan_range_limits_path()

        self.make_equipment_info()
        self.setup_default_channel_info()
        self.setup_artificial_channel_info()
        self._catalog_snapshot = self._capture_current_catalog_snapshot(
            initial_device_snapshot.profile_name
        )
        self.device_channel_catalog = self._mutable_router_catalog(
            self._catalog_snapshot
        )
        self.command_router = DeviceCommandRouter(main_window=self, parent=self)
        self.inject_command_router_metadata()
        self.command_router.publish_catalog(self.device_channel_catalog)

        self.scanlist = ScanList(
            info=self.info,
            setter_equipment_info=self.setter_equipment_info,
            main_window=self,
            getter_equipment_info=self.getter_equipment_info,
        )
        self.scanlist.show()
        self.scanlist.setWindowTitle("Scan List")
        self.scan_list_button.clicked.connect(self.open_scan_list_window_clicked)
        self.scan_range_button.clicked.connect(self.open_scan_range_window_clicked)
        self.scan_range_window = ScanRangeWindow(
            limits_path=self.scan_range_limits_path,
            on_reload_clicked=self.reload_scan_range_limits,
            parent=None,
        )
        self.update_serial_counter()              # set it once on start-up
        self.reload_scan_range_limits()

        if not hasattr(self, "devices_grid_layout"):
            # Backward-compatible fallback for older UI files.
            self.devices_grid_layout = QtWidgets.QGridLayout()
            self.horizontalLayout_3.addLayout(self.devices_grid_layout)

        self.devices_grid_layout.setHorizontalSpacing(6)
        self.devices_grid_layout.setVerticalSpacing(4)

        self.open_equipment_buttons = []
        self._equipment_buttons_by_label = {}
        self._equipment_button_windows = {}
        initial_button_plan = self._prepare_device_button_reconciliation(self.equips)
        self._commit_device_button_reconciliation(initial_button_plan)
        self._finalize_device_button_reconciliation(initial_button_plan)

    def _show_and_focus_window(self, window):
        if window is None:
            return

        window.show()
        if hasattr(window, "isMinimized") and window.isMinimized():
            window.showNormal()
        if hasattr(window, "raise_"):
            window.raise_()
        if hasattr(window, "activateWindow"):
            window.activateWindow()

    def open_scan_list_window_clicked(self):
        self._show_and_focus_window(self.scanlist)

    def _prepare_device_button_reconciliation(self, equipment):
        """Build a side-effect-minimal button plan before changing the layout."""

        existing_buttons = dict(getattr(self, "_equipment_buttons_by_label", {}))
        existing_windows = dict(getattr(self, "_equipment_button_windows", {}))
        planned_buttons = {}
        created_buttons = []
        old_window_titles = []

        try:
            for equipment_name, window in equipment.items():
                window_title = getattr(window, "windowTitle", None)
                old_window_titles.append(
                    (
                        window,
                        window_title() if callable(window_title) else None,
                    )
                )
                window.setWindowTitle(equipment_name)
                if (
                    equipment_name in existing_buttons
                    and existing_windows.get(equipment_name) is window
                ):
                    button = existing_buttons[equipment_name]
                else:
                    button = QtWidgets.QPushButton()
                    button.setText(equipment_name)
                    button.clicked.connect(
                        lambda _checked=False, target=window: (
                            self._show_and_focus_window(target)
                        )
                    )
                    created_buttons.append(button)
                planned_buttons[equipment_name] = button
        except Exception as prepare_error:
            rollback_failures = []
            for window, title in reversed(old_window_titles):
                if title is not None:
                    try:
                        window.setWindowTitle(title)
                    except Exception as rollback_error:
                        rollback_failures.append(
                            ("restore prepared device window title", rollback_error)
                        )
            for button in created_buttons:
                try:
                    button.deleteLater()
                except Exception as rollback_error:
                    rollback_failures.append(
                        ("dispose prepared device button", rollback_error)
                    )
            if rollback_failures:
                raise DeviceCatalogRollbackError(
                    prepare_error,
                    rollback_failures,
                ) from prepare_error
            raise

        return {
            "old_buttons": existing_buttons,
            "old_windows": existing_windows,
            "new_buttons": planned_buttons,
            "new_windows": dict(equipment),
            "created_buttons": tuple(created_buttons),
            "old_window_titles": tuple(old_window_titles),
        }

    def _commit_device_button_reconciliation(self, plan) -> None:
        """Apply one prepared layout replacement, restoring the old grid on error."""

        old_buttons = plan["old_buttons"]
        new_buttons = plan["new_buttons"]
        layout = self.devices_grid_layout

        try:
            for button in old_buttons.values():
                layout.removeWidget(button)
            for index, button in enumerate(new_buttons.values()):
                layout.addWidget(button, index // 6, index % 6)
        except Exception as commit_error:
            try:
                self._rollback_device_button_reconciliation(plan)
            except DeviceCatalogRollbackError as rollback_error:
                raise DeviceCatalogRollbackError(
                    commit_error,
                    rollback_error.failures,
                ) from commit_error
            raise

        retained_ids = {id(button) for button in new_buttons.values()}
        for button in old_buttons.values():
            if id(button) in retained_ids:
                continue
            button.hide()

        self._equipment_buttons_by_label = dict(new_buttons)
        self._equipment_button_windows = dict(plan["new_windows"])
        self.open_equipment_buttons = list(new_buttons.values())

    def _rollback_device_button_reconciliation(self, plan) -> None:
        layout = self.devices_grid_layout
        rollback_failures = []

        def attempt(operation, callback):
            try:
                callback()
            except Exception as rollback_error:
                rollback_failures.append((operation, rollback_error))

        for button in plan["new_buttons"].values():
            attempt("remove staged device button", lambda button=button: layout.removeWidget(button))
        for index, button in enumerate(plan["old_buttons"].values()):
            attempt("show previous device button", button.show)
            attempt(
                "restore previous device button",
                lambda index=index, button=button: layout.addWidget(
                    button,
                    index // 6,
                    index % 6,
                ),
            )
        for button in plan["created_buttons"]:
            try:
                button.clicked.disconnect()
            except (RuntimeError, TypeError):
                pass
            attempt("hide staged device button", button.hide)
            attempt(
                "detach staged device button",
                lambda button=button: button.setParent(None),
            )
            attempt("dispose staged device button", button.deleteLater)
        self._equipment_buttons_by_label = dict(plan["old_buttons"])
        self._equipment_button_windows = dict(plan["old_windows"])
        self.open_equipment_buttons = list(plan["old_buttons"].values())
        if rollback_failures:
            raise DeviceCatalogRollbackError(
                RuntimeError("device button reconciliation rollback failed"),
                rollback_failures,
            )

    @staticmethod
    def _finalize_device_button_reconciliation(plan) -> None:
        retained_ids = {id(button) for button in plan["new_buttons"].values()}
        for button in plan["old_buttons"].values():
            if id(button) in retained_ids:
                continue
            try:
                button.clicked.disconnect()
                button.setParent(None)
                button.deleteLater()
            except (RuntimeError, TypeError):
                pass

    @staticmethod
    def _restore_prepared_device_titles(plan) -> None:
        rollback_failures = []
        for window, title in reversed(plan["old_window_titles"]):
            if title is not None:
                try:
                    window.setWindowTitle(title)
                except Exception as rollback_error:
                    rollback_failures.append(
                        ("restore prepared device window title", rollback_error)
                    )
        if rollback_failures:
            raise DeviceCatalogRollbackError(
                RuntimeError("device title restoration failed"),
                rollback_failures,
            )

    # artificial channels

    def setup_artificial_channel_info(self):
        self.artificial_channel_logic = ArtificialChannelLogic(
            write_channel=self.write_info,
            read_channel=self.read_info,
            parent=self,
            original_channel_x_limits=(-1.0, 1.0),
            original_channel_y_limits=(-1.0, 1.0),
            should_abort_ramp=self.should_abort_artificial_ramp,
            resolve_device_label=self.resolve_device_label_for_channel,
        )
        self.update_artificial_channel_scan_info()

        self.artificial_channel_2d = ArtificialChannel2D(
            logic=self.artificial_channel_logic,
            setter_equipment_info=self.setter_equipment_info,
            on_config_preflight=self.preflight_artificial_channel_config,
            on_config_applied=self.on_artificial_channel_config_applied,
            parent=None,
        )
        self.artificialChanne2D_button.clicked.connect(
            self.open_artificial_channel_2d_window
        )

    def open_artificial_channel_2d_window(self):
        self._show_and_focus_window(self.artificial_channel_2d)

    def update_artificial_channel_scan_info(self):
        self.equations = dict(self.artificial_channel_logic.equations)
        self.setter_equipment_info_for_scanning["artificial_channel"] = {
            channel: self._make_artificial_channel_writer(channel)
            for channel in self.artificial_channel_logic.artificial_channels
        }
        self.getter_equipment_info_for_scanning["artificial_channel"] = {
            channel: self._make_artificial_channel_reader(channel)
            for channel in self.artificial_channel_logic.artificial_channels
        }
        self.setter_equipment_info["artificial_channel"] = list(
            self.artificial_channel_logic.artificial_channels
        )
        self.getter_equipment_info["artificial_channel"] = list(
            self.artificial_channel_logic.artificial_channels
        )

    def setup_default_channel_info(self):
        self.setter_equipment_info_for_scanning["default"] = {
            "wait": self._set_default_wait,
            "count": self._set_default_count,
        }
        self.getter_equipment_info_for_scanning["default"] = {}
        self.setter_equipment_info["default"] = ["wait", "count"]
        self.getter_equipment_info["default"] = []

    def _set_default_wait(self, val):
        time.sleep(float(val))

    def _set_default_count(self, _val):
        time.sleep(0.01)

    def _default_scan_range_limits_path(self) -> str:
        root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
        return os.path.join(root_dir, self.SCAN_RANGE_CONFIG_FILENAME)

    def open_scan_range_window_clicked(self):
        self._show_and_focus_window(self.scan_range_window)

    def mark_skip_next_scan_read_from_global_limit(self):
        self._skip_next_scan_read_from_global_limit = True

    def should_abort_artificial_ramp(self) -> bool:
        return bool(getattr(self, "_force_stop_requested", False))

    def resolve_device_label_for_channel(self, channel_name: str) -> str:
        for label in self.setter_equipment_info_for_scanning.keys():
            if channel_name.startswith(f"{label}_"):
                return label
        for label in self.getter_equipment_info_for_scanning.keys():
            if channel_name.startswith(f"{label}_"):
                return label
        if "_" in channel_name:
            return channel_name.rsplit("_", 1)[0]
        return channel_name

    def consume_skip_read_for_scan_from_global_limit(self) -> bool:
        skip = bool(self._skip_next_scan_read_from_global_limit)
        self._skip_next_scan_read_from_global_limit = False
        return skip

    def reset_skip_next_scan_read_from_global_limit(self) -> None:
        self._skip_next_scan_read_from_global_limit = False

    def _parse_scan_range_bound(self, value, default):
        if value is None:
            return float(default)

        if isinstance(value, str):
            text = value.strip().lower()
            if text == "":
                return float(default)
            if text in {"+inf", "inf", "+infinity", "infinity"}:
                return float("inf")
            if text in {"-inf", "-infinity"}:
                return float("-inf")
            return float(text)

        return float(value)

    def _parse_scan_range_entries(self, payload):
        if isinstance(payload, dict):
            entries = payload.get("limits", [])
        elif isinstance(payload, list):
            entries = payload
        else:
            raise ValueError("scan-range JSON must be a list or a dict with a 'limits' list.")

        if not isinstance(entries, list):
            raise ValueError("'limits' must be a list.")

        parsed_limits = {}
        warnings = []

        for index, entry in enumerate(entries):
            if not isinstance(entry, dict):
                warnings.append(f"entry[{index}] ignored: not an object.")
                continue

            device_name = str(entry.get("device_name", "")).strip()
            channel = str(entry.get("channel", "")).strip()
            if device_name == "" or channel == "":
                warnings.append(
                    f"entry[{index}] ignored: device_name/channel is required."
                )
                continue

            try:
                low_limit = self._parse_scan_range_bound(
                    entry.get("low_limit"), default=float("-inf")
                )
                high_limit = self._parse_scan_range_bound(
                    entry.get("high_limit"), default=float("inf")
                )
            except (TypeError, ValueError) as exc:
                warnings.append(f"entry[{index}] ignored: invalid bound value ({exc}).")
                continue

            if low_limit > high_limit:
                warnings.append(
                    f"entry[{index}] ignored: low_limit {low_limit} > high_limit {high_limit}."
                )
                continue

            parsed_limits[(device_name, channel)] = (low_limit, high_limit)

        return parsed_limits, warnings

    def _set_scan_range_status(self, message):
        if hasattr(self, "scan_range_window"):
            self.scan_range_window.set_status(message)

    def reload_scan_range_limits(self):
        file_path = self.scan_range_limits_path

        try:
            with open(file_path, "r", encoding="utf-8") as handle:
                payload = json.load(handle)
        except FileNotFoundError:
            message = (
                f"[ScanRange] Config file not found at '{file_path}'. "
                "Keeping previous limits."
            )
            print(message)
            self._set_scan_range_status(message)
            return False
        except (json.JSONDecodeError, OSError) as exc:
            message = (
                f"[ScanRange] Failed to read '{file_path}': {exc}. "
                "Keeping previous limits."
            )
            print(message)
            self._set_scan_range_status(message)
            return False

        try:
            parsed_limits, warnings = self._parse_scan_range_entries(payload)
        except Exception as exc:
            message = (
                f"[ScanRange] Invalid config format in '{file_path}': {exc}. "
                "Keeping previous limits."
            )
            print(message)
            self._set_scan_range_status(message)
            return False

        for warning in warnings:
            print(f"[ScanRange] {warning}")

        self.scan_range_limits = parsed_limits
        self._refresh_active_scan_range_limits()
        message = (
            f"[ScanRange] Loaded {len(parsed_limits)} limit entries from '{file_path}'."
        )
        print(message)
        self._set_scan_range_status(message)
        return True

    def on_artificial_channel_config_applied(self):
        self.apply_device_snapshot(self._applied_device_snapshot)
        self.equations = dict(self.artificial_channel_logic.equations)

    def preflight_artificial_channel_config(
        self,
        *,
        original_channel_x_name,
        original_channel_y_name,
        artificial_channel_x_name,
        artificial_channel_y_name,
    ):
        del original_channel_x_name, original_channel_y_name
        if self._catalog_mutation_in_progress:
            raise DeviceCatalogBusyError(("catalog replacement in progress",))
        self._ensure_catalog_mutation_idle()
        staged_snapshot = self._build_catalog_snapshot(
            self._applied_device_snapshot,
            artificial_channels=(
                artificial_channel_x_name,
                artificial_channel_y_name,
            ),
        )
        self._preflight_catalog_references(staged_snapshot)

    def write_artificial_channel(self, val, variable):
        self.artificial_channel_logic.set_channel_value(variable, val)

    def read_artificial_channel(self, variable):
        return self.artificial_channel_logic.read_channel_value(variable)

    def _make_artificial_channel_writer(self, channel_name):
        return lambda val, channel_name=channel_name: self.write_artificial_channel(
            val, channel_name
        )

    def _make_artificial_channel_reader(self, channel_name):
        return lambda channel_name=channel_name: self.read_artificial_channel(
            channel_name
        )

    ## Adding devices and make equipment info

    @property
    def current_catalog_snapshot(self) -> DeviceCatalogSnapshot:
        return self._catalog_snapshot

    @property
    def catalog_snapshot(self) -> DeviceCatalogSnapshot:
        return self._catalog_snapshot

    def _build_catalog_snapshot(
        self,
        device_snapshot,
        *,
        artificial_channels=None,
    ) -> DeviceCatalogSnapshot:
        equipment = dict(device_snapshot.equipment)
        setter_filters = dict(device_snapshot.setter_filters)
        getter_filters = dict(device_snapshot.getter_filters)
        setter_callables = {}
        getter_callables = {}

        for equipment_label, equipment_window in equipment.items():
            setters, getters = self._discover_variables_dictionary(
                equipment_window,
                equipment_label,
                setter_filters.get(equipment_label),
                getter_filters.get(equipment_label),
            )
            setter_callables[equipment_label] = setters
            getter_callables[equipment_label] = getters

        setter_callables["default"] = {
            "wait": self._set_default_wait,
            "count": self._set_default_count,
        }
        getter_callables["default"] = {}

        if hasattr(self, "artificial_channel_logic"):
            if artificial_channels is None:
                artificial_channels = self.artificial_channel_logic.artificial_channels
            setter_callables["artificial_channel"] = {
                channel: self._make_artificial_channel_writer(channel)
                for channel in artificial_channels
            }
            getter_callables["artificial_channel"] = {
                channel: self._make_artificial_channel_reader(channel)
                for channel in artificial_channels
            }

        setter_channels = {
            label: tuple(channels)
            for label, channels in (
                (label, channel_map.keys())
                for label, channel_map in setter_callables.items()
            )
        }
        getter_channels = {
            label: tuple(channels)
            for label, channels in (
                (label, channel_map.keys())
                for label, channel_map in getter_callables.items()
            )
        }
        router_catalog = self.build_device_channel_catalog(
            setter_channels,
            getter_channels,
        )
        active_scan_range_limits = self._build_active_scan_range_limits(
            setter_channels
        )
        return DeviceCatalogSnapshot(
            profile_name=device_snapshot.profile_name,
            equipment=equipment,
            setter_filters=setter_filters,
            getter_filters=getter_filters,
            setter_callables=setter_callables,
            getter_callables=getter_callables,
            setter_channels=setter_channels,
            getter_channels=getter_channels,
            router_catalog=router_catalog,
            active_scan_range_limits=active_scan_range_limits,
        )

    def _capture_current_catalog_snapshot(self, profile_name):
        return DeviceCatalogSnapshot(
            profile_name=profile_name,
            equipment=self.equips,
            setter_filters=self.equips_set_channels,
            getter_filters=self.equips_get_channels,
            setter_callables=self.setter_equipment_info_for_scanning,
            getter_callables=self.getter_equipment_info_for_scanning,
            setter_channels=self.setter_equipment_info,
            getter_channels=self.getter_equipment_info,
            router_catalog=self.build_device_channel_catalog(),
            active_scan_range_limits=self._build_active_scan_range_limits(
                self.setter_equipment_info
            ),
        )

    @staticmethod
    def _mutable_router_catalog(snapshot):
        return {
            label: {
                "readable": list(channel_info["readable"]),
                "writable": list(channel_info["writable"]),
            }
            for label, channel_info in snapshot.router_catalog.items()
        }

    @staticmethod
    def _mutable_callable_maps(values):
        return {
            label: dict(channel_map)
            for label, channel_map in values.items()
        }

    @staticmethod
    def _mutable_channel_maps(values):
        return {
            label: list(channel_names)
            for label, channel_names in values.items()
        }

    def _install_catalog_snapshot(self, snapshot) -> None:
        self.equips = dict(snapshot.equipment)
        self.equips_set_channels = dict(snapshot.setter_filters)
        self.equips_get_channels = dict(snapshot.getter_filters)
        self.setter_equipment_info_for_scanning = self._mutable_callable_maps(
            snapshot.setter_callables
        )
        self.getter_equipment_info_for_scanning = self._mutable_callable_maps(
            snapshot.getter_callables
        )
        self.setter_equipment_info = self._mutable_channel_maps(
            snapshot.setter_channels
        )
        self.getter_equipment_info = self._mutable_channel_maps(
            snapshot.getter_channels
        )
        self.device_channel_catalog = self._mutable_router_catalog(snapshot)
        self.active_scan_range_limits = dict(snapshot.active_scan_range_limits)
        self._catalog_snapshot = snapshot

    @staticmethod
    def _full_channels(channel_maps):
        return {
            f"{device_label}_{channel_name}"
            for device_label, channel_names in channel_maps.items()
            for channel_name in channel_names
        }

    def _build_active_scan_range_limits(self, setter_channels):
        writable = {
            (device_label, channel_name)
            for device_label, channel_names in setter_channels.items()
            for channel_name in channel_names
        }
        return {
            key: bounds
            for key, bounds in self.scan_range_limits.items()
            if key in writable
        }

    def _refresh_active_scan_range_limits(self) -> None:
        snapshot = getattr(self, "_catalog_snapshot", None)
        if snapshot is None:
            self.active_scan_range_limits = {}
            return
        active_limits = self._build_active_scan_range_limits(
            snapshot.setter_channels
        )
        snapshot = replace(
            snapshot,
            active_scan_range_limits=active_limits,
        )
        self._catalog_snapshot = snapshot
        self.active_scan_range_limits = dict(snapshot.active_scan_range_limits)

    @staticmethod
    def _normalize_reference_descriptions(references):
        if references is None:
            return ()
        if isinstance(references, str):
            return (references,)
        if isinstance(references, dict):
            references = references.values()
        try:
            return tuple(str(reference) for reference in references)
        except TypeError:
            return (str(references),)

    def _scanlist_channel_references(self, removed_setters, removed_getters):
        scanlist = getattr(self, "scanlist", None)
        finder = getattr(scanlist, "find_channel_references", None)
        if not callable(finder):
            return ()
        references = finder(
            removed_setters=removed_setters,
            removed_getters=removed_getters,
        )
        return self._normalize_reference_descriptions(references)

    def _artificial_channel_references(self, removed_setters):
        artificial_window = getattr(self, "artificial_channel_2d", None)
        logic = getattr(self, "artificial_channel_logic", None)
        if artificial_window is None or logic is None:
            return ()

        candidates = (
            ("artificial-channel active x", logic.original_channel_x_name),
            ("artificial-channel active y", logic.original_channel_y_name),
            (
                "artificial-channel draft x",
                artificial_window.ocx_nested_menu.name
                or artificial_window.ocx_nested_menu.unresolved_name,
            ),
            (
                "artificial-channel draft y",
                artificial_window.ocy_nested_menu.name
                or artificial_window.ocy_nested_menu.unresolved_name,
            ),
        )
        return tuple(
            f"{source}: {channel_name}"
            for source, channel_name in candidates
            if channel_name in removed_setters
        )

    def _device_owned_catalog_references(
        self,
        removed_setters,
        removed_getters,
        removed_device_labels,
    ):
        references = []
        for equipment in self.equips.values():
            finder = getattr(equipment, "find_catalog_references", None)
            if not callable(finder):
                continue
            references.extend(
                self._normalize_reference_descriptions(
                    finder(
                        removed_setters=removed_setters,
                        removed_getters=removed_getters,
                        removed_device_labels=removed_device_labels,
                    )
                )
            )
        return tuple(references)

    def find_channel_references(
        self,
        removed_setters,
        removed_getters=(),
        removed_device_labels=(),
    ):
        removed_setters = set(removed_setters)
        removed_getters = set(removed_getters)
        removed_device_labels = set(removed_device_labels)
        references = (
            *self._scanlist_channel_references(removed_setters, removed_getters),
            *self._artificial_channel_references(removed_setters),
            *self._device_owned_catalog_references(
                removed_setters,
                removed_getters,
                removed_device_labels,
            ),
        )
        return tuple(dict.fromkeys(references))

    def _reference_device_label(self, channel_name):
        candidates = [
            label
            for label in self._catalog_snapshot.equipment
            if channel_name.startswith(f"{label}_")
        ]
        if not candidates:
            return None
        return max(candidates, key=len)

    def find_device_references(self, label):
        snapshot = self._catalog_snapshot
        removed_setters = {
            f"{label}_{channel_name}"
            for channel_name in snapshot.setter_channels.get(label, ())
        }
        removed_getters = {
            f"{label}_{channel_name}"
            for channel_name in snapshot.getter_channels.get(label, ())
        }
        references = list(
            self.find_channel_references(
                removed_setters,
                removed_getters,
                removed_device_labels={label},
            )
        )

        scanlist = getattr(self, "scanlist", None)
        scan_finder = getattr(scanlist, "find_device_references", None)
        if callable(scan_finder):
            references.extend(
                self._normalize_reference_descriptions(scan_finder(label))
            )
        reference_uses = getattr(scanlist, "reference_uses", None)
        if callable(reference_uses):
            for reference in reference_uses():
                if self._reference_device_label(str(reference.channel)) == label:
                    references.append(str(reference))

        artificial_window = getattr(self, "artificial_channel_2d", None)
        logic = getattr(self, "artificial_channel_logic", None)
        if artificial_window is not None and logic is not None:
            candidates = (
                ("artificial-channel active x", logic.original_channel_x_name),
                ("artificial-channel active y", logic.original_channel_y_name),
                (
                    "artificial-channel draft x",
                    artificial_window.ocx_nested_menu.name
                    or artificial_window.ocx_nested_menu.unresolved_name,
                ),
                (
                    "artificial-channel draft y",
                    artificial_window.ocy_nested_menu.name
                    or artificial_window.ocy_nested_menu.unresolved_name,
                ),
            )
            references.extend(
                f"{source}: {channel_name}"
                for source, channel_name in candidates
                if self._reference_device_label(channel_name) == label
            )
        return tuple(dict.fromkeys(references))

    def _preflight_catalog_references(self, new_snapshot):
        old_snapshot = getattr(self, "_catalog_snapshot", None)
        if old_snapshot is None:
            return
        removed_setters = self._full_channels(old_snapshot.setter_channels) - (
            self._full_channels(new_snapshot.setter_channels)
        )
        removed_getters = self._full_channels(old_snapshot.getter_channels) - (
            self._full_channels(new_snapshot.getter_channels)
        )
        removed_labels = set(old_snapshot.equipment) - set(new_snapshot.equipment)
        if not removed_setters and not removed_getters and not removed_labels:
            return
        references = list(
            self.find_channel_references(
                removed_setters,
                removed_getters,
                removed_device_labels=removed_labels,
            )
        )
        for label in sorted(removed_labels):
            references.extend(self.find_device_references(label))
        references = tuple(dict.fromkeys(references))
        if references:
            raise DeviceCatalogReferenceError(
                removed_setters,
                removed_getters,
                references,
                removed_labels,
            )

    @staticmethod
    def _router_metadata_objects(equipment):
        objects = []
        seen = set()

        def append_object(obj):
            if obj is None or id(obj) in seen:
                return
            seen.add(id(obj))
            objects.append(obj)
            children_getter = getattr(obj, "command_router_children", None)
            if callable(children_getter):
                children = tuple(children_getter())
            else:
                children = (
                    getattr(obj, "logic", None),
                    getattr(obj, "hardware", None),
                )
            for child in children:
                append_object(child)

        for equipment_window in equipment:
            append_object(equipment_window)
        return tuple(objects)

    def _capture_router_metadata_for_replacements(self, equipment):
        old_equipment = getattr(self, "equips", {})
        new_labels_by_identity = {}
        for device_label, equipment_window in equipment.items():
            new_labels_by_identity.setdefault(id(equipment_window), []).append(device_label)
        for old_label, equipment_window in old_equipment.items():
            new_labels = new_labels_by_identity.get(id(equipment_window), ())
            if new_labels and old_label not in new_labels:
                raise DeviceCatalogError(
                    "device labels are stable; applying one existing instance under "
                    f"a new label is unsupported ({old_label!r} -> {new_labels[0]!r})"
                )
        if any(len(labels) > 1 for labels in new_labels_by_identity.values()):
            raise DeviceCatalogError(
                "one device instance cannot be published under multiple labels"
            )

        replacements = {
            device_label: equipment_window
            for device_label, equipment_window in equipment.items()
            if old_equipment.get(device_label) is not equipment_window
        }
        removed = {
            device_label: equipment_window
            for device_label, equipment_window in old_equipment.items()
            if equipment.get(device_label) is not equipment_window
        }
        replacement_objects = self._router_metadata_objects(replacements.values())
        retained_object_ids = {
            id(obj) for obj in self._router_metadata_objects(equipment.values())
        }
        removed_objects = tuple(
            obj
            for obj in self._router_metadata_objects(removed.values())
            if id(obj) not in retained_object_ids
        )
        affected_objects = (*replacement_objects, *removed_objects)
        for obj in affected_objects:
            configure_router = getattr(obj, "configure_command_router", None)
            detach_router = getattr(obj, "detach_command_router", None)
            if callable(configure_router) and not callable(detach_router):
                raise DeviceCatalogError(
                    "runtime catalog replacement requires objects with "
                    "configure_command_router() to also implement an idempotent "
                    "detach_command_router() rollback hook"
                )
        missing = object()
        captured = []
        for obj in affected_objects:
            captured.append(
                (
                    obj,
                    {
                        attribute: getattr(obj, attribute, missing)
                        for attribute in (
                            "command_router",
                            "device_label",
                            "source_device",
                        )
                    },
                )
            )
        return {
            "replacements": replacements,
            "removed": removed,
            "replacement_objects": replacement_objects,
            "removed_objects": removed_objects,
            "missing": missing,
            "captured": tuple(captured),
        }

    @staticmethod
    def _restore_router_metadata(capture) -> None:
        missing = capture["missing"]
        for obj, attributes in reversed(capture["captured"]):
            for attribute, value in attributes.items():
                try:
                    if value is missing:
                        delattr(obj, attribute)
                    else:
                        setattr(obj, attribute, value)
                except (AttributeError, RuntimeError):
                    pass

    def _inject_router_metadata_for_replacements(self, equipment, capture):
        visited_objects = set()
        for device_label, equipment_window in capture["replacements"].items():
            self._inject_command_router_into_object(
                equipment_window,
                device_label=device_label,
                visited_objects=visited_objects,
            )

    def _detach_router_metadata_from_objects(self, objects):
        for obj in reversed(tuple(objects)):
            detach_router = getattr(obj, "detach_command_router", None)
            if callable(detach_router):
                detach_router()
            for attribute in ("command_router", "device_label", "source_device"):
                try:
                    delattr(obj, attribute)
                except (AttributeError, RuntimeError):
                    pass

    def _restore_removed_router_attachments(self, capture):
        visited_objects = set()
        for device_label, equipment_window in capture["removed"].items():
            self._inject_command_router_into_object(
                equipment_window,
                device_label=device_label,
                visited_objects=visited_objects,
            )

    def _refresh_scanlist_catalog(self, snapshot):
        scanlist = getattr(self, "scanlist", None)
        if scanlist is None:
            return
        setter_info = self._mutable_channel_maps(snapshot.setter_channels)
        getter_info = self._mutable_channel_maps(snapshot.getter_channels)
        refresh_catalog = getattr(scanlist, "refresh_catalog", None)
        if callable(refresh_catalog):
            refresh_catalog(setter_info, getter_info)
            return
        scanlist.setter_equipment_info_updated(setter_info)
        scanlist.getter_equipment_info_updated(getter_info)

    def _restore_artificial_channel_choices(self, snapshot, selections):
        artificial_window = getattr(self, "artificial_channel_2d", None)
        if artificial_window is None:
            return
        artificial_window.refresh_channel_choices(
            self._mutable_channel_maps(snapshot.setter_channels)
        )
        artificial_window.ocx_nested_menu.set_chosen_one(selections[0])
        artificial_window.ocy_nested_menu.set_chosen_one(selections[1])

    def _ensure_catalog_mutation_idle(self) -> None:
        scanlist = getattr(self, "scanlist", None)
        blockers_getter = getattr(scanlist, "catalog_mutation_blockers", None)
        if not callable(blockers_getter):
            return
        blockers = tuple(blockers_getter())
        if blockers:
            raise DeviceCatalogBusyError(blockers)

    def apply_device_snapshot(
        self,
        device_snapshot,
    ) -> DeviceCatalogSnapshot:
        """Atomically rebuild and publish every catalog consumer from one input."""

        if QtCore.QThread.currentThread() is not self.thread():
            raise RuntimeError("device catalog snapshots must be applied on the UI thread")

        if self._catalog_mutation_in_progress:
            raise DeviceCatalogBusyError(("catalog replacement in progress",))
        self._catalog_mutation_in_progress = True
        try:
            return self._apply_device_snapshot_transaction(device_snapshot)
        finally:
            self._catalog_mutation_in_progress = False

    def _apply_device_snapshot_transaction(self, device_snapshot):
        self._ensure_catalog_mutation_idle()
        staged_snapshot = self._build_catalog_snapshot(device_snapshot)
        self._preflight_catalog_references(staged_snapshot)

        metadata_capture = self._capture_router_metadata_for_replacements(
            staged_snapshot.equipment
        )
        try:
            self._inject_router_metadata_for_replacements(
                staged_snapshot.equipment,
                metadata_capture,
            )
            button_plan = self._prepare_device_button_reconciliation(
                staged_snapshot.equipment
            )
        except Exception as apply_error:
            rollback_failures = []
            for operation, callback in (
                (
                    "detach staged router metadata",
                    lambda: self._detach_router_metadata_from_objects(
                        metadata_capture["replacement_objects"]
                    ),
                ),
                (
                    "restore router metadata attributes",
                    lambda: self._restore_router_metadata(metadata_capture),
                ),
            ):
                try:
                    callback()
                except Exception as rollback_error:
                    rollback_failures.append((operation, rollback_error))
            if rollback_failures:
                raise DeviceCatalogRollbackError(
                    apply_error,
                    rollback_failures,
                ) from apply_error
            raise

        old_snapshot = self._catalog_snapshot
        old_device_snapshot = self._applied_device_snapshot
        artificial_window = getattr(self, "artificial_channel_2d", None)
        old_artificial_selections = (
            artificial_window.ocx_nested_menu.name
            or artificial_window.ocx_nested_menu.unresolved_name,
            artificial_window.ocy_nested_menu.name
            or artificial_window.ocy_nested_menu.unresolved_name,
        )
        artificial_refreshed = False
        scanlist_refreshed = False
        installed = False
        button_commit_attempted = False
        publication_attempted = False
        removed_metadata_detached = False

        try:
            removed_metadata_detached = True
            self._detach_router_metadata_from_objects(
                metadata_capture["removed_objects"]
            )
            self._install_catalog_snapshot(staged_snapshot)
            self._applied_device_snapshot = device_snapshot
            installed = True

            if artificial_window is not None:
                artificial_refreshed = True
                artificial_window.refresh_channel_choices(
                    self._mutable_channel_maps(staged_snapshot.setter_channels)
                )

            scanlist_refreshed = True
            self._refresh_scanlist_catalog(staged_snapshot)
            button_commit_attempted = True
            self._commit_device_button_reconciliation(button_plan)
            publication_attempted = True
            self.command_router.publish_catalog(self.device_channel_catalog)
        except Exception as apply_error:
            rollback_failures = []

            def attempt_rollback(operation, callback):
                try:
                    callback()
                except Exception as rollback_error:
                    rollback_failures.append((operation, rollback_error))

            if button_commit_attempted:
                attempt_rollback(
                    "restore device buttons",
                    lambda: self._rollback_device_button_reconciliation(button_plan),
                )
            if installed:
                def restore_authoritative_snapshot():
                    self._install_catalog_snapshot(old_snapshot)
                    self._applied_device_snapshot = old_device_snapshot

                attempt_rollback(
                    "restore authoritative catalog snapshot",
                    restore_authoritative_snapshot,
                )
            if scanlist_refreshed:
                attempt_rollback(
                    "restore scan-list consumers",
                    lambda: self._refresh_scanlist_catalog(old_snapshot),
                )
            if artificial_refreshed:
                attempt_rollback(
                    "restore artificial-channel choices",
                    lambda: self._restore_artificial_channel_choices(
                        old_snapshot,
                        old_artificial_selections,
                    ),
                )
            attempt_rollback(
                "restore device window titles",
                lambda: self._restore_prepared_device_titles(button_plan),
            )
            attempt_rollback(
                "detach staged router metadata",
                lambda: self._detach_router_metadata_from_objects(
                    metadata_capture["replacement_objects"]
                ),
            )
            attempt_rollback(
                "restore router metadata attributes",
                lambda: self._restore_router_metadata(metadata_capture),
            )
            if removed_metadata_detached:
                attempt_rollback(
                    "restore removed router attachments",
                    lambda: self._restore_removed_router_attachments(metadata_capture),
                )
            if publication_attempted:
                attempt_rollback(
                    "republish previous router catalog",
                    lambda: self.command_router.publish_catalog(
                        self._mutable_router_catalog(old_snapshot)
                    ),
                )
            if rollback_failures:
                raise DeviceCatalogRollbackError(
                    apply_error,
                    rollback_failures,
                ) from apply_error
            raise

        self._finalize_device_button_reconciliation(button_plan)
        return staged_snapshot

    def make_equipment_info(self):
        for key, equipment in self.equips.items():

            set_variable, get_variable = self.make_variables_dictionary(equipment, key)

            self.setter_equipment_info_for_scanning[key] = set_variable
            self.getter_equipment_info_for_scanning[key] = get_variable

            self.setter_equipment_info[key] = list(set_variable.keys())
            self.getter_equipment_info[key] = list(get_variable.keys())

    def make_variables_dictionary(self, equipment, equipment_label):
        return self._discover_variables_dictionary(
            equipment,
            equipment_label,
            self.equips_set_channels.get(equipment_label),
            self.equips_get_channels.get(equipment_label),
        )

    def _discover_variables_dictionary(
        self,
        equipment,
        equipment_label,
        requested_set_channels,
        requested_get_channels,
    ):
        get_variables = {}
        set_variables = {}
        logic = getattr(equipment, "logic", None)
        if logic is None:
            return set_variables, get_variables

        for method_name in dir(logic):
            if not method_name.startswith(("get_", "set_")):
                continue
            try:
                static_member = inspect.getattr_static(logic, method_name)
            except AttributeError:
                continue
            if isinstance(static_member, (staticmethod, classmethod)):
                static_member = static_member.__func__
            if not callable(static_member):
                # Avoid evaluating properties and arbitrary descriptors merely
                # because their names resemble scan channels.
                continue
            method = getattr(logic, method_name)
            if not callable(method):
                continue
            if method_name.startswith("get_") and self._is_valid_getter(method):
                get_variables[method_name[4:]] = method
            elif method_name.startswith("set_") and self._is_valid_setter(method):
                set_variables[method_name[4:]] = method
        
        set_variables = self.filter_scan_channels(set_variables, requested_set_channels)
        get_variables = self.filter_scan_channels(get_variables, requested_get_channels)
        return set_variables, get_variables

    def _is_valid_getter(self, method) -> bool:
        signature = self._safe_signature(method)
        if signature is None:
            return False

        positional_params = [
            parameter
            for parameter in signature.parameters.values()
            if parameter.kind
            in (
                inspect.Parameter.POSITIONAL_ONLY,
                inspect.Parameter.POSITIONAL_OR_KEYWORD,
            )
        ]
        has_varargs = any(
            parameter.kind == inspect.Parameter.VAR_POSITIONAL
            for parameter in signature.parameters.values()
        )
        return (not has_varargs) and len(positional_params) == 0

    def _is_valid_setter(self, method) -> bool:
        signature = self._safe_signature(method)
        if signature is None:
            return False

        positional_params = [
            parameter
            for parameter in signature.parameters.values()
            if parameter.kind
            in (
                inspect.Parameter.POSITIONAL_ONLY,
                inspect.Parameter.POSITIONAL_OR_KEYWORD,
            )
        ]
        has_varargs = any(
            parameter.kind == inspect.Parameter.VAR_POSITIONAL
            for parameter in signature.parameters.values()
        )
        return (not has_varargs) and len(positional_params) == 1

    def _safe_signature(self, method):
        try:
            return inspect.signature(method)
        except (TypeError, ValueError):
            return None

    def filter_scan_channels(self, variables, requested_channels):
        """
        Keep only requested scan channels for one equipment label.

        - If requested_channels is None: keep all channels.
        - Unknown channels are silently skipped.
        - Accepts both plain names ("AO0") and prefixed names ("set_AO0"/"get_AO0").
        """
        if requested_channels is None:
            return variables

        normalized = set()
        for channel in requested_channels:
            if not isinstance(channel, str):
                continue
            name = channel.strip()
            if not name:
                continue
            if name.startswith("set_") or name.startswith("get_"):
                name = name[4:]
            normalized.add(name)

        return {key: value for key, value in variables.items() if key in normalized}

    def build_device_channel_catalog(self, setter_info=None, getter_info=None):
        if setter_info is None:
            setter_info = self.setter_equipment_info
        if getter_info is None:
            getter_info = self.getter_equipment_info
        device_names = set(setter_info) | set(getter_info)
        catalog = {}
        for device_name in sorted(device_names):
            catalog[device_name] = {
                "readable": list(getter_info.get(device_name, [])),
                "writable": list(setter_info.get(device_name, [])),
            }
        return catalog

    def refresh_device_catalog(self):
        snapshot = self.apply_device_snapshot(self._applied_device_snapshot)
        return self._mutable_router_catalog(snapshot)

    def get_device_channel_catalog(self):
        return self._mutable_router_catalog(self._catalog_snapshot)

    def inject_command_router_metadata(self):
        visited_objects = set()
        for device_label, equipment in self.equips.items():
            self._inject_command_router_into_object(
                equipment,
                device_label=device_label,
                visited_objects=visited_objects,
            )

        if hasattr(self, "artificial_channel_logic"):
            self._inject_command_router_into_object(
                self.artificial_channel_logic,
                device_label="artificial_channel",
                visited_objects=visited_objects,
            )

    def _inject_command_router_into_object(
        self,
        obj,
        *,
        device_label,
        visited_objects,
    ):
        if obj is None:
            return

        object_id = id(obj)
        if object_id in visited_objects:
            return
        visited_objects.add(object_id)

        configure_router = getattr(obj, "configure_command_router", None)
        configured_root = False
        if callable(configure_router):
            signature = self._safe_signature(configure_router)
            accepts_source_device = signature is not None and (
                "source_device" in signature.parameters
                or any(
                    parameter.kind == inspect.Parameter.VAR_KEYWORD
                    for parameter in signature.parameters.values()
                )
            )
            if accepts_source_device:
                configure_router(self.command_router, source_device=device_label)
            else:
                configure_router(self.command_router)
            configured_root = True

        try:
            obj.device_label = device_label
        except Exception:
            pass

        try:
            obj.command_router = self.command_router
        except Exception:
            pass

        if configured_root:
            return

        children_getter = getattr(obj, "command_router_children", None)
        if callable(children_getter):
            children = tuple(children_getter())
        else:
            children = (
                getattr(obj, "logic", None),
                getattr(obj, "hardware", None),
            )
        for child in children:
            if child is not None:
                self._inject_command_router_into_object(
                    child,
                    device_label=device_label,
                    visited_objects=visited_objects,
                )

    # def execute_default(self, val, master): #Mohamed Chamge
    #     """
    #     Execute default functions 
    #     wait - sleep for the giving second
    #     count - repeat the scan
    #     """
    #     for index, character in enumerate(master):
    #         if character == "_":
    #             variable = master[index + 1 : :]
    #     if variable == "wait":
    #         time.sleep(val)
    #     elif variable == "count":
    #         time.sleep(0.01)


    # Read and write info

    # def write_info(self, val, master):
    #     if np.isnan(val):
    #         return
    #     for key, equipment in self.setter_equipment_info_for_scanning.items():
    #         if key in master:  # key = lockin_0  master = lockin_0_amplitude
    #             time.sleep(0.01)
    #             variable = self.get_variable(master)
    #             equipment[variable](val)

    def write_info(self, val, master):
        if self._is_nan_value(val):
            return

        for label, setters in self.setter_equipment_info_for_scanning.items():
            # exact prefix match: label followed by an underscore
            if master.startswith(f"{label}_"): #elif
                variable = self.get_variable(master, label)
                scan_range_limits = getattr(self, "active_scan_range_limits", {})
                limits = scan_range_limits.get((label, variable))
                if limits is not None:
                    low_limit, high_limit = limits
                    numeric_val = float(val)
                    if numeric_val < low_limit or numeric_val > high_limit:
                        print(
                            f"[ScanRange] Denied write '{master}'={numeric_val} "
                            f"outside [{low_limit}, {high_limit}]."
                        )
                        self.mark_skip_next_scan_read_from_global_limit()
                        return
                try:
                    setters[variable](val)
                except KeyError:
                    raise KeyError(
                        f"Variable '{variable}' not found in equipment '{label}'. "
                        f"Check your channel name '{master}'."
                    )
                return

        raise KeyError(f"No equipment found that matches channel '{master}'.")

    def _is_nan_value(self, value) -> bool:
        try:
            return bool(np.isnan(value))
        except (TypeError, ValueError):
            return False

    # def get_variable(self, name):
    #     counter = False
    #     for index, character in enumerate(name):
    #         if character == "_":
    #             if counter:
    #                 return name[index + 1 : :]
    #             else:
    #                 counter = True
    
    def get_variable(self, full_name: str, equip_label: str) -> str:
        """
        Given a full channel name like 'nidaq_0_voltage'
        and its equipment label 'nidaq_0', return 'voltage'.
        Works for labels that contain zero-or-many underscores.
        """
        prefix = f"{equip_label}_"
        return full_name[len(prefix):]   # everything after the prefix

    # def read_info(self, slave):

    #     if slave == "none":
    #         result = np.nan
    #     else:
    #         for key, equipment in self.getter_equipment_info_for_scanning.items():
    #             if key in slave:
    #                 variable = self.get_variable(slave)
    #                 result = equipment[variable]()
    #             # result=equipment.read_info(slave[-1])

    #     return result

    def read_info(self, slave):
        if slave == "none":
            return np.nan

        for label, getters in self.getter_equipment_info_for_scanning.items():
            if slave.startswith(f"{label}_"):
                variable = self.get_variable(slave, label)
                try:
                    return getters[variable]()        # return the read value
                except KeyError:
                    raise KeyError(
                        f"Variable '{variable}' not found in equipment '{label}'. "
                        f"Check your channel name '{slave}'."
                    ) from None

        raise KeyError(f"No equipment found that matches channel '{slave}'.")
    
    
    _serial_regex = re.compile(r"^(\d{4})_")      # “0000_ …”

    def _serial_folder(self) -> str:
        """
        Folder in which data files are stored, trimmed & normalised.
        Falls back to cwd if the text box is empty.
        """
        txt = ""
        if hasattr(self, "save_info_path"):
            if callable(getattr(self.save_info_path, "toPlainText", None)):
                txt = self.save_info_path.toPlainText()
            elif callable(getattr(self.save_info_path, "text", None)):
                txt = self.save_info_path.text()

        txt = txt.strip().strip('"')
        return os.path.normpath(txt) if txt else os.getcwd()

    def update_serial_counter(self):
        """
        Look at existing files and set ScanList.serial accordingly.
        """
        folder = self._serial_folder()
        if not os.path.isdir(folder):
            self.scanlist.serial.setValue(0)
            return

        max_found = -1
        for fname in os.listdir(folder):
            m = self._serial_regex.match(fname)
            if m:
                num = int(m.group(1))
                if num > max_found:
                    max_found = num

        self.scanlist.serial.setValue(max_found + 1 if max_found >= 0 else 0)

    def stop_equipments_for_scanning(self):
        device_manager = getattr(self, "device_manager", None)
        if device_manager is not None:
            report = device_manager.stop_for_scan()
            self._raise_lifecycle_failures(report)
            return report
        for name, equipment in self.equips.items():
            if hasattr(equipment, "stop_scan"):
                equipment.stop_scan()

    def start_equipments(self):
        self._force_stop_requested = False
        device_manager = getattr(self, "device_manager", None)
        if device_manager is not None:
            report = device_manager.start_after_scan()
            self._raise_lifecycle_failures(report)
            return report
        for name, equipment in self.equips.items():
            if hasattr(equipment, "start_scan"):
                equipment.start_scan()

    def force_stop_equipments(self):
        self._force_stop_requested = True
        device_manager = getattr(self, "device_manager", None)
        if device_manager is not None:
            report = device_manager.force_stop_all()
            self._raise_lifecycle_failures(report)
            return report
        for name, equipment in self.equips.items():
            if hasattr(equipment, "force_stop"):
                equipment.force_stop()

    def _report_lifecycle_failures(self, report):
        if report is None:
            return
        for failure in getattr(report, "failures", ()):
            print(f"Device lifecycle warning: {failure.describe()}")

    def _raise_lifecycle_failures(self, report):
        self._report_lifecycle_failures(report)
        if getattr(report, "failures", ()):
            raise DeviceLifecycleError(report)

    def shutdown_session(self, *, timeout_ms=10000):
        """Quiesce scans and tear down all devices exactly once.

        This method intentionally does not ask for confirmation so the launcher
        can reuse it on abnormal event-loop exits. A timeout leaves devices and
        shared runtimes untouched because safe quiescence was not proven.
        """
        if self._session_shutdown_complete:
            return self._session_shutdown_report
        if self._session_shutdown_in_progress:
            raise RuntimeError("application shutdown is already in progress")

        self._session_shutdown_in_progress = True
        try:
            self.scanlist.shutdown(timeout_ms=timeout_ms)

            if hasattr(self, "artificial_channel_2d"):
                self.artificial_channel_2d.close()
            if hasattr(self, "scan_range_window"):
                self.scan_range_window.close()

            if self.device_manager is not None:
                report = self.device_manager.teardown_all()
                self._report_lifecycle_failures(report)
                self._session_shutdown_report = report
                if report.failures:
                    raise DeviceLifecycleError(report)
            else:
                self.force_stop_equipments()
                self.stop_equipments_for_scanning()
                for equipment_name, equipment in self.equips.items():
                    print("Terminating", equipment_name)
                    equipment.terminate_dev()
                    equipment.close()
                report = None

            self._session_shutdown_report = report
            self._session_shutdown_complete = True
            print("Main Window terminated.")
            return report
        finally:
            self._session_shutdown_in_progress = False


    def closeEvent(self, event: QtGui.QCloseEvent):          # <- keep the type
        reply = QtWidgets.QMessageBox.question(
            self,
            "Confirm Exit",
            "Quit the application and disconnect all equipment?",
            QtWidgets.QMessageBox.StandardButton.Yes
            | QtWidgets.QMessageBox.StandardButton.No,
            QtWidgets.QMessageBox.StandardButton.No,         # default = “No”
        )

        if reply == QtWidgets.QMessageBox.StandardButton.Yes:
            try:
                self.shutdown_session()
            except (
                DeviceLifecycleError,
                ScanListShutdownTimeoutError,
                ScanListShutdownStopError,
            ) as exc:
                QtWidgets.QMessageBox.critical(
                    self,
                    "Shutdown Delayed",
                    "Equipment was not disconnected because safe scan "
                    f"shutdown did not complete: {exc}",
                )
                event.ignore()
                return
            event.accept()                                   # actually close
        else:
            event.ignore()                                   # stay open

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow(info=ScanInfo)
    window.show()
    window.setWindowTitle("Main Window")
    app.exec()
