import inspect
import json
import os
import re
import sys
import time
from copy import deepcopy

import numpy as np
from PyQt6 import QtWidgets, uic, QtCore, QtGui


# from sr830.sr830_main import SR830
# from sr860.sr860_main import SR860
# from nidaq.nidaq_main import NIDAQ
# from keithley24xx.keithley24xx_main import Keithley24xx
# from k10cr1.k10cr1_main import K10CR1
# from tlpm.tlpm_main import TLPM

from .scan_info import *
from .scanlist import ScanList
from .artificial_channel_logic import ArtificialChannelLogic
from .artificial_channel_2d_main import ArtificialChannel2D
from .device_command_router import DeviceCommandRouter
from .scan_range_main import ScanRangeWindow


#Select Virtual Environment under zmeter_venv\.venv\Scripts\python.exe
class MainWindow(QtWidgets.QWidget):
    print("Initiating the Program")
    SCAN_RANGE_CONFIG_FILENAME = "scan_range_limits.json"

    def __init__(
        self,
        info=None,
        save_path=None,
        backup_main_path=None,
        equips=None,
        equips_set_channels=None,
        equips_get_channels=None,
    ):
        super().__init__()
        print("Loading the Main Window")
        uic.loadUi(r"core/ui/mainwindow.ui", self)
        self.info = info
        
        # ------------------------------------------------------------
        # Configuration previously hard-coded here is now supplied via
        # the constructor arguments so that users can customise the
        # application without editing this file.  See `start_zmeter.py`.

        # Paths
        if save_path is None:
            save_path = os.path.join(os.getcwd(), "data")
        self.save_path = save_path

        if backup_main_path is None:
            self.backup_bool = False
        else:
            self.backup_bool = True
            self.backup_main_path = backup_main_path

        # Reflect the paths in the UI elements that were generated by
        # QtDesigner.
        self.ppt_path.setPlainText(os.path.join(self.save_path, "log.pptx"))
        self.save_info_path.setPlainText(self.save_path)

        # Keep a live alias used by Scan._backup_subfolder(), so user edits in
        # the UI are always read at save time.
        self.backup_path = self.backup_Path
        if self.backup_bool:
            default_backup_path = os.path.join(
                self.backup_main_path, os.path.basename(os.getcwd())
            )
            self.backup_Path.setPlainText(default_backup_path)

        # Equipment instances (already connected) provided by caller.
        # Fall back to an empty dict for headless usage/testing.
        self.equips = equips if equips is not None else {}
        self.equips_set_channels = (
            equips_set_channels if equips_set_channels is not None else {}
        )
        self.equips_get_channels = (
            equips_get_channels if equips_get_channels is not None else {}
        )
        # ------------------------------------------------------------

        # {equipment name (e.g. lockin_0) : {variable name : set method},....}
        self.setter_equipment_info_for_scanning = {}
        # {equipment name (e.g. lockin_0) : {variable name : get method},....}
        self.getter_equipment_info_for_scanning = {}
        # {equipment(lockin_0) : [list of variable name]}
        self.setter_equipment_info = {}
        # {equipment : [list of variable name]}
        self.getter_equipment_info = {}
        self.device_channel_catalog = {}
        self.scan_range_limits = {}
        self._skip_next_scan_read_from_global_limit = False
        self._force_stop_requested = False
        self.scan_range_limits_path = self._default_scan_range_limits_path()

        self.make_equipment_info()
        self.setup_default_channel_info()
        self.setup_artificial_channel_info()
        self.command_router = DeviceCommandRouter(main_window=self, parent=self)
        self.inject_command_router_metadata()
        self.refresh_device_catalog()

        self.scanlist = ScanList(
            info=self.info,
            setter_equipment_info=self.setter_equipment_info,
            main_window=self,
            getter_equipment_info=self.getter_equipment_info,
        )
        self.scanlist.show()
        self.scanlist.setWindowTitle("Scan List")
        self.scan_list_button.clicked.connect(self.open_scan_list_window_clicked)
        self.scan_range_button.clicked.connect(self.open_scan_range_window_clicked)
        self.scan_range_window = ScanRangeWindow(
            limits_path=self.scan_range_limits_path,
            on_reload_clicked=self.reload_scan_range_limits,
            parent=None,
        )
        self.update_serial_counter()              # set it once on start-up
        self.reload_scan_range_limits()

        if not hasattr(self, "devices_grid_layout"):
            # Backward-compatible fallback for older UI files.
            self.devices_grid_layout = QtWidgets.QGridLayout()
            self.horizontalLayout_3.addLayout(self.devices_grid_layout)

        self.devices_grid_layout.setHorizontalSpacing(6)
        self.devices_grid_layout.setVerticalSpacing(4)

        self.open_equipment_buttons = []
        for index, (equipment_name, equipment) in enumerate(self.equips.items()):
            # equipment.show()
            equipment.setWindowTitle(equipment_name)
            open_button = QtWidgets.QPushButton()
            open_button.setText(equipment_name)
            self.open_equipment_buttons.append(open_button)
            row = index // 6
            column = index % 6
            self.devices_grid_layout.addWidget(open_button, row, column)
            open_button.clicked.connect(
                lambda _checked=False, window=equipment: self._show_and_focus_window(window)
            )

    def _show_and_focus_window(self, window):
        if window is None:
            return

        window.show()
        if hasattr(window, "isMinimized") and window.isMinimized():
            window.showNormal()
        if hasattr(window, "raise_"):
            window.raise_()
        if hasattr(window, "activateWindow"):
            window.activateWindow()

    def open_scan_list_window_clicked(self):
        self._show_and_focus_window(self.scanlist)

    # artificial channels

    def setup_artificial_channel_info(self):
        self.artificial_channel_logic = ArtificialChannelLogic(
            write_channel=self.write_info,
            read_channel=self.read_info,
            parent=self,
            original_channel_x_limits=(-1.0, 1.0),
            original_channel_y_limits=(-1.0, 1.0),
            should_abort_ramp=self.should_abort_artificial_ramp,
            resolve_device_label=self.resolve_device_label_for_channel,
        )
        self.update_artificial_channel_scan_info()

        self.artificial_channel_2d = ArtificialChannel2D(
            logic=self.artificial_channel_logic,
            setter_equipment_info=self.setter_equipment_info,
            on_config_applied=self.on_artificial_channel_config_applied,
            parent=None,
        )
        self.artificialChanne2D_button.clicked.connect(
            self.open_artificial_channel_2d_window
        )

    def open_artificial_channel_2d_window(self):
        self._show_and_focus_window(self.artificial_channel_2d)

    def update_artificial_channel_scan_info(self):
        self.equations = dict(self.artificial_channel_logic.equations)
        self.setter_equipment_info_for_scanning["artificial_channel"] = {
            channel: self._make_artificial_channel_writer(channel)
            for channel in self.artificial_channel_logic.artificial_channels
        }
        self.getter_equipment_info_for_scanning["artificial_channel"] = {
            channel: self._make_artificial_channel_reader(channel)
            for channel in self.artificial_channel_logic.artificial_channels
        }
        self.setter_equipment_info["artificial_channel"] = list(
            self.artificial_channel_logic.artificial_channels
        )
        self.getter_equipment_info["artificial_channel"] = list(
            self.artificial_channel_logic.artificial_channels
        )

    def setup_default_channel_info(self):
        self.setter_equipment_info_for_scanning["default"] = {
            "wait": self._set_default_wait,
            "count": self._set_default_count,
        }
        self.getter_equipment_info_for_scanning["default"] = {}
        self.setter_equipment_info["default"] = ["wait", "count"]
        self.getter_equipment_info["default"] = []

    def _set_default_wait(self, val):
        time.sleep(float(val))

    def _set_default_count(self, _val):
        time.sleep(0.01)

    def _default_scan_range_limits_path(self) -> str:
        root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
        return os.path.join(root_dir, self.SCAN_RANGE_CONFIG_FILENAME)

    def open_scan_range_window_clicked(self):
        self._show_and_focus_window(self.scan_range_window)

    def mark_skip_next_scan_read_from_global_limit(self):
        self._skip_next_scan_read_from_global_limit = True

    def should_abort_artificial_ramp(self) -> bool:
        return bool(getattr(self, "_force_stop_requested", False))

    def resolve_device_label_for_channel(self, channel_name: str) -> str:
        for label in self.setter_equipment_info_for_scanning.keys():
            if channel_name.startswith(f"{label}_"):
                return label
        for label in self.getter_equipment_info_for_scanning.keys():
            if channel_name.startswith(f"{label}_"):
                return label
        if "_" in channel_name:
            return channel_name.rsplit("_", 1)[0]
        return channel_name

    def consume_skip_read_for_scan_from_global_limit(self) -> bool:
        skip = bool(self._skip_next_scan_read_from_global_limit)
        self._skip_next_scan_read_from_global_limit = False
        return skip

    def reset_skip_next_scan_read_from_global_limit(self) -> None:
        self._skip_next_scan_read_from_global_limit = False

    def _parse_scan_range_bound(self, value, default):
        if value is None:
            return float(default)

        if isinstance(value, str):
            text = value.strip().lower()
            if text == "":
                return float(default)
            if text in {"+inf", "inf", "+infinity", "infinity"}:
                return float("inf")
            if text in {"-inf", "-infinity"}:
                return float("-inf")
            return float(text)

        return float(value)

    def _parse_scan_range_entries(self, payload):
        if isinstance(payload, dict):
            entries = payload.get("limits", [])
        elif isinstance(payload, list):
            entries = payload
        else:
            raise ValueError("scan-range JSON must be a list or a dict with a 'limits' list.")

        if not isinstance(entries, list):
            raise ValueError("'limits' must be a list.")

        parsed_limits = {}
        warnings = []

        for index, entry in enumerate(entries):
            if not isinstance(entry, dict):
                warnings.append(f"entry[{index}] ignored: not an object.")
                continue

            device_name = str(entry.get("device_name", "")).strip()
            channel = str(entry.get("channel", "")).strip()
            if device_name == "" or channel == "":
                warnings.append(
                    f"entry[{index}] ignored: device_name/channel is required."
                )
                continue

            try:
                low_limit = self._parse_scan_range_bound(
                    entry.get("low_limit"), default=float("-inf")
                )
                high_limit = self._parse_scan_range_bound(
                    entry.get("high_limit"), default=float("inf")
                )
            except (TypeError, ValueError) as exc:
                warnings.append(f"entry[{index}] ignored: invalid bound value ({exc}).")
                continue

            if low_limit > high_limit:
                warnings.append(
                    f"entry[{index}] ignored: low_limit {low_limit} > high_limit {high_limit}."
                )
                continue

            parsed_limits[(device_name, channel)] = (low_limit, high_limit)

        return parsed_limits, warnings

    def _set_scan_range_status(self, message):
        if hasattr(self, "scan_range_window"):
            self.scan_range_window.set_status(message)

    def reload_scan_range_limits(self):
        file_path = self.scan_range_limits_path

        try:
            with open(file_path, "r", encoding="utf-8") as handle:
                payload = json.load(handle)
        except FileNotFoundError:
            message = (
                f"[ScanRange] Config file not found at '{file_path}'. "
                "Keeping previous limits."
            )
            print(message)
            self._set_scan_range_status(message)
            return False
        except (json.JSONDecodeError, OSError) as exc:
            message = (
                f"[ScanRange] Failed to read '{file_path}': {exc}. "
                "Keeping previous limits."
            )
            print(message)
            self._set_scan_range_status(message)
            return False

        try:
            parsed_limits, warnings = self._parse_scan_range_entries(payload)
        except Exception as exc:
            message = (
                f"[ScanRange] Invalid config format in '{file_path}': {exc}. "
                "Keeping previous limits."
            )
            print(message)
            self._set_scan_range_status(message)
            return False

        for warning in warnings:
            print(f"[ScanRange] {warning}")

        self.scan_range_limits = parsed_limits
        message = (
            f"[ScanRange] Loaded {len(parsed_limits)} limit entries from '{file_path}'."
        )
        print(message)
        self._set_scan_range_status(message)
        return True

    def on_artificial_channel_config_applied(self):
        self.update_artificial_channel_scan_info()
        self.refresh_device_catalog()
        if hasattr(self, "scanlist"):
            self.scanlist.setter_equipment_info_updated(self.setter_equipment_info)
            self.scanlist.getter_equipment_info_updated(self.getter_equipment_info)

    def write_artificial_channel(self, val, variable):
        self.artificial_channel_logic.set_channel_value(variable, val)

    def read_artificial_channel(self, variable):
        return self.artificial_channel_logic.read_channel_value(variable)

    def _make_artificial_channel_writer(self, channel_name):
        return lambda val, channel_name=channel_name: self.write_artificial_channel(
            val, channel_name
        )

    def _make_artificial_channel_reader(self, channel_name):
        return lambda channel_name=channel_name: self.read_artificial_channel(
            channel_name
        )

    ## Adding devices and make equipment info

    def make_equipment_info(self):
        for key, equipment in self.equips.items():

            set_variable, get_variable = self.make_variables_dictionary(equipment, key)

            self.setter_equipment_info_for_scanning[key] = set_variable
            self.getter_equipment_info_for_scanning[key] = get_variable

            self.setter_equipment_info[key] = list(set_variable.keys())
            self.getter_equipment_info[key] = list(get_variable.keys())

    def make_variables_dictionary(self, equipment, equipment_label):
        get_variables = {}
        set_variables = {}
        logic = getattr(equipment, "logic", None)
        if logic is None:
            return set_variables, get_variables

        for method_name in dir(logic):
            method = getattr(logic, method_name)
            if not callable(method):
                continue
            if method_name.startswith("get_") and self._is_valid_getter(method):
                get_variables[method_name[4:]] = method
            elif method_name.startswith("set_") and self._is_valid_setter(method):
                set_variables[method_name[4:]] = method
        
        requested_set_channels = self.equips_set_channels.get(equipment_label)
        requested_get_channels = self.equips_get_channels.get(equipment_label)

        set_variables = self.filter_scan_channels(set_variables, requested_set_channels)
        get_variables = self.filter_scan_channels(get_variables, requested_get_channels)
        return set_variables, get_variables

    def _is_valid_getter(self, method) -> bool:
        signature = self._safe_signature(method)
        if signature is None:
            return False

        positional_params = [
            parameter
            for parameter in signature.parameters.values()
            if parameter.kind
            in (
                inspect.Parameter.POSITIONAL_ONLY,
                inspect.Parameter.POSITIONAL_OR_KEYWORD,
            )
        ]
        has_varargs = any(
            parameter.kind == inspect.Parameter.VAR_POSITIONAL
            for parameter in signature.parameters.values()
        )
        return (not has_varargs) and len(positional_params) == 0

    def _is_valid_setter(self, method) -> bool:
        signature = self._safe_signature(method)
        if signature is None:
            return False

        positional_params = [
            parameter
            for parameter in signature.parameters.values()
            if parameter.kind
            in (
                inspect.Parameter.POSITIONAL_ONLY,
                inspect.Parameter.POSITIONAL_OR_KEYWORD,
            )
        ]
        has_varargs = any(
            parameter.kind == inspect.Parameter.VAR_POSITIONAL
            for parameter in signature.parameters.values()
        )
        return (not has_varargs) and len(positional_params) == 1

    def _safe_signature(self, method):
        try:
            return inspect.signature(method)
        except (TypeError, ValueError):
            return None

    def filter_scan_channels(self, variables, requested_channels):
        """
        Keep only requested scan channels for one equipment label.

        - If requested_channels is None: keep all channels.
        - Unknown channels are silently skipped.
        - Accepts both plain names ("AO0") and prefixed names ("set_AO0"/"get_AO0").
        """
        if requested_channels is None:
            return variables

        normalized = set()
        for channel in requested_channels:
            if not isinstance(channel, str):
                continue
            name = channel.strip()
            if not name:
                continue
            if name.startswith("set_") or name.startswith("get_"):
                name = name[4:]
            normalized.add(name)

        return {key: value for key, value in variables.items() if key in normalized}

    def build_device_channel_catalog(self):
        device_names = set(self.setter_equipment_info) | set(self.getter_equipment_info)
        catalog = {}
        for device_name in sorted(device_names):
            catalog[device_name] = {
                "readable": list(self.getter_equipment_info.get(device_name, [])),
                "writable": list(self.setter_equipment_info.get(device_name, [])),
            }
        return catalog

    def refresh_device_catalog(self):
        self.device_channel_catalog = self.build_device_channel_catalog()
        if hasattr(self, "command_router"):
            self.command_router.publish_catalog(self.device_channel_catalog)
        return self.device_channel_catalog

    def get_device_channel_catalog(self):
        return deepcopy(self.device_channel_catalog)

    def inject_command_router_metadata(self):
        visited_objects = set()
        for device_label, equipment in self.equips.items():
            self._inject_command_router_into_object(
                equipment,
                device_label=device_label,
                visited_objects=visited_objects,
            )

        if hasattr(self, "artificial_channel_logic"):
            self._inject_command_router_into_object(
                self.artificial_channel_logic,
                device_label="artificial_channel",
                visited_objects=visited_objects,
            )

    def _inject_command_router_into_object(
        self,
        obj,
        *,
        device_label,
        visited_objects,
    ):
        if obj is None:
            return

        object_id = id(obj)
        if object_id in visited_objects:
            return
        visited_objects.add(object_id)

        configure_router = getattr(obj, "configure_command_router", None)
        if callable(configure_router):
            try:
                configure_router(self.command_router, source_device=device_label)
            except TypeError:
                configure_router(self.command_router)

        try:
            obj.device_label = device_label
        except Exception:
            pass

        try:
            obj.command_router = self.command_router
        except Exception:
            pass

        for child_attr in ("logic", "hardware"):
            child = getattr(obj, child_attr, None)
            if child is not None:
                self._inject_command_router_into_object(
                    child,
                    device_label=device_label,
                    visited_objects=visited_objects,
                )

    # def execute_default(self, val, master): #Mohamed Chamge
    #     """
    #     Execute default functions 
    #     wait - sleep for the giving second
    #     count - repeat the scan
    #     """
    #     for index, character in enumerate(master):
    #         if character == "_":
    #             variable = master[index + 1 : :]
    #     if variable == "wait":
    #         time.sleep(val)
    #     elif variable == "count":
    #         time.sleep(0.01)


    # Read and write info

    # def write_info(self, val, master):
    #     if np.isnan(val):
    #         return
    #     for key, equipment in self.setter_equipment_info_for_scanning.items():
    #         if key in master:  # key = lockin_0  master = lockin_0_amplitude
    #             time.sleep(0.01)
    #             variable = self.get_variable(master)
    #             equipment[variable](val)

    def write_info(self, val, master):
        if self._is_nan_value(val):
            return

        for label, setters in self.setter_equipment_info_for_scanning.items():
            # exact prefix match: label followed by an underscore
            if master.startswith(f"{label}_"): #elif
                variable = self.get_variable(master, label)
                scan_range_limits = getattr(self, "scan_range_limits", {})
                limits = scan_range_limits.get((label, variable))
                if limits is not None:
                    low_limit, high_limit = limits
                    numeric_val = float(val)
                    if numeric_val < low_limit or numeric_val > high_limit:
                        print(
                            f"[ScanRange] Denied write '{master}'={numeric_val} "
                            f"outside [{low_limit}, {high_limit}]."
                        )
                        self.mark_skip_next_scan_read_from_global_limit()
                        return
                try:
                    setters[variable](val)
                except KeyError:
                    raise KeyError(
                        f"Variable '{variable}' not found in equipment '{label}'. "
                        f"Check your channel name '{master}'."
                    )
                return

        raise KeyError(f"No equipment found that matches channel '{master}'.")

    def _is_nan_value(self, value) -> bool:
        try:
            return bool(np.isnan(value))
        except (TypeError, ValueError):
            return False

    # def get_variable(self, name):
    #     counter = False
    #     for index, character in enumerate(name):
    #         if character == "_":
    #             if counter:
    #                 return name[index + 1 : :]
    #             else:
    #                 counter = True
    
    def get_variable(self, full_name: str, equip_label: str) -> str:
        """
        Given a full channel name like 'nidaq_0_voltage'
        and its equipment label 'nidaq_0', return 'voltage'.
        Works for labels that contain zero-or-many underscores.
        """
        prefix = f"{equip_label}_"
        return full_name[len(prefix):]   # everything after the prefix

    # def read_info(self, slave):

    #     if slave == "none":
    #         result = np.nan
    #     else:
    #         for key, equipment in self.getter_equipment_info_for_scanning.items():
    #             if key in slave:
    #                 variable = self.get_variable(slave)
    #                 result = equipment[variable]()
    #             # result=equipment.read_info(slave[-1])

    #     return result

    def read_info(self, slave):
        if slave == "none":
            return np.nan

        for label, getters in self.getter_equipment_info_for_scanning.items():
            if slave.startswith(f"{label}_"):
                variable = self.get_variable(slave, label)
                try:
                    return getters[variable]()        # return the read value
                except KeyError:
                    raise KeyError(
                        f"Variable '{variable}' not found in equipment '{label}'. "
                        f"Check your channel name '{slave}'."
                    ) from None

        raise KeyError(f"No equipment found that matches channel '{slave}'.")
    
    
    _serial_regex = re.compile(r"^(\d{4})_")      # “0000_ …”

    def _serial_folder(self) -> str:
        """
        Folder in which data files are stored, trimmed & normalised.
        Falls back to cwd if the text box is empty.
        """
        txt = ""
        if hasattr(self, "save_info_path"):
            if callable(getattr(self.save_info_path, "toPlainText", None)):
                txt = self.save_info_path.toPlainText()
            elif callable(getattr(self.save_info_path, "text", None)):
                txt = self.save_info_path.text()

        txt = txt.strip().strip('"')
        return os.path.normpath(txt) if txt else os.getcwd()

    def update_serial_counter(self):
        """
        Look at existing files and set ScanList.serial accordingly.
        """
        folder = self._serial_folder()
        if not os.path.isdir(folder):
            self.scanlist.serial.setValue(0)
            return

        max_found = -1
        for fname in os.listdir(folder):
            m = self._serial_regex.match(fname)
            if m:
                num = int(m.group(1))
                if num > max_found:
                    max_found = num

        self.scanlist.serial.setValue(max_found + 1 if max_found >= 0 else 0)

    def stop_equipments_for_scanning(self):
        # need fix
        for name, equipment in self.equips.items():
            if hasattr(equipment, "stop_scan"):
                equipment.stop_scan()

    def start_equipments(self):
        self._force_stop_requested = False
        for name, equipment in self.equips.items():
            if hasattr(equipment, "start_scan"):
                equipment.start_scan()

    def force_stop_equipments(self):
        self._force_stop_requested = True
        for name, equipment in self.equips.items():
            if hasattr(equipment, "force_stop"):
                equipment.force_stop()


    def closeEvent(self, event: QtGui.QCloseEvent):          # <- keep the type
        reply = QtWidgets.QMessageBox.question(
            self,
            "Confirm Exit",
            "Quit the application and disconnect all equipment?",
            QtWidgets.QMessageBox.StandardButton.Yes
            | QtWidgets.QMessageBox.StandardButton.No,
            QtWidgets.QMessageBox.StandardButton.No,         # default = “No”
        )

        if reply == QtWidgets.QMessageBox.StandardButton.Yes:
            # proceed with the regular shutdown
            if hasattr(self, "artificial_channel_2d"):
                self.artificial_channel_2d.close()
            if hasattr(self, "scan_range_window"):
                self.scan_range_window.close()
            self.scanlist.shutdown()
            self.force_stop_equipments()
            self.stop_equipments_for_scanning()
            for equipment_name, equipment in self.equips.items():
                print("Terminating", equipment_name)
                equipment.terminate_dev()
                equipment.close()
            print("Main Window terminated.")
            event.accept()                                   # actually close
        else:
            event.ignore()                                   # stay open

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow(info=ScanInfo)
    window.show()
    window.setWindowTitle("Main Window")
    app.exec()
